### ISSUE TITLE
时空守卫技能报错

### ISSUE THREAD

**Issue by wang1986one** [yutio888/tome-chn#10]
T1技能自动切换主武器和副武器，此时报错

[LOG]	555 施展了 重叠灵矢 。
[ARCHERY ACQUIRE TARGETS WITH]	elm longbow	quiver of elm arrows	nil	nil
[SHOOT] speed	0.8	=>	800
[SOUND] loading from	/data/sound/actions/arrow.ogg	:=:	sound "/data/sound/actions/arrow.ogg" : <static>
[ARCHERY SHOOT]	555	2870	using weapon:	elm longbow	ammo:	quiver of elm arrows	offweapon:	nil	pf_weapon:	nil
[ARCHERY SHOOT dofire] Shooting weapon:	elm longbow	to:	44	38
FROM 	/mod/addons/orcs/superload/mod/class/Projectile.lua	loading previous!
Adding entity	23087	after	2870
[PARTY] New member, add after	555's temporal clone	555
Adding entity	23100	after	2870
Added unique	mod.class.NPC/player	::	1
[ARCHERY ACQUIRE TARGETS WITH]	elm longbow	quiver of elm arrows	nil	nil
[SHOOT] speed	0.8	=>	800
[ARCHERY SHOOT]	555's temporal clone	23100	using weapon:	elm longbow	ammo:	quiver of elm arrows	offweapon:	nil	pf_weapon:	nil
[ARCHERY SHOOT dofire] Shooting weapon:	elm longbow	to:	44	38
Adding entity	23101	after	23100
[PARTY] New member, add after	555's temporal clone	555
Adding entity	23121	after	2870
Added unique	mod.class.NPC/player	::	2
[ARCHERY ACQUIRE TARGETS WITH]	elm longbow	quiver of elm arrows	nil	nil
[SHOOT] speed	0.8	=>	800
[ARCHERY SHOOT]	555's temporal clone	23121	using weapon:	elm longbow	ammo:	quiver of elm arrows	offweapon:	nil	pf_weapon:	nil
[ARCHERY SHOOT dofire] Shooting weapon:	elm longbow	to:	44	38
Adding entity	23122	after	23121
[TARGET] Passing target	orb spinner	from	orb weaver	to	555
[TARGET] Passing target	orb spinner	from	orb weaver	to	555
[TARGET] Passing target	orb weaver	from	orb weaver	to	555
[ATTACK ARCHERY]	23087	 to 	orb weaver	 :: 	17.980679818734	5	2	::	0.83266615305568
checkHit	20	vs	7	=> chance to hit	83
logMsgCheck	#Source# misses #target#.
logMsgTrans	#Source# misses #target#.
[logerr]555的重叠灵矢 misses 球蛛编织者.
[LOG]	555的重叠灵矢 misses 球蛛编织者.
[ATTACK ARCHERY]	23122	 to 	orb weaver	 :: 	17.980679818734	5	2	::	0.83266615305568
checkHit	20	vs	7	=> chance to hit	83
[ATTACK ARCHERY] raw dam	17.980679818734	versus	2	with APR	5
[ATTACK ARCHERY] after armor	17.980679818734
[ATTACK ARCHERY] after range	20
[PHYS CRIT %] axe accuracy bonus	20	7	=	2.6
[PHYS CRIT %]	3.6
[ATTACK ARCHERY] after crit	20
[ATTACK ARCHERY] after mult	16.653323061114
[ATTACK ARCHERY] after hook	16.653323061114
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #WHITE#7 物理#LAST# 伤害。
[logerr]555的重叠灵矢的时空复制体 击中 球蛛编织者 造成 #WHITE#7 物理#LAST# 伤害。
[LOG]	555的重叠灵矢的时空复制体 击中 球蛛编织者 造成 #WHITE#7 物理#LAST# 伤害。
[logerr]
[LOG]	
[PlayerProfile] eventDisconnected
[logerr]%s casts %s.
[LOG]	555 施展了 扭曲灵刃 。
Loading tile	player/human_female/right_hand_04_01.png
Loading tile	player/human_female/left_hand_03_01.png
[logerr]%s warps space-time to equip: %s.
##Use Talent Lua Error##	T_WARP_BLADE	Actor:	2870	555
Lua Error: /engine/interface/ActorTalents.lua:333: /engine/interface/ActorTalents.lua:306: /engine/interface/ActorTalents.lua:173: data-chn123/logs/class.lua:1607: attempt to call method 'gsub' (a nil value)
stack traceback:
	data-chn123/logs/class.lua:1607: in function 'fct'
	/data-chn123/logs.lua:22: in function 'trans'
	/engine/LogDisplay.lua:126: in function 'logdisplay'
	/mod/class/uiset/Minimalist.lua:495: in function 'log'
	/mod/class/Game.lua:1525: in function 'logSeen'
	/mod/class/Actor.lua:3840: in function 'quickSwitchWeapons'
	/data/talents/chronomancy/chronomancer.lua:259: in function 'doWardenWeaponSwap'
	/data/talents/chronomancy/blade-threading.lua:39: in function </data/talents/chronomancy/blade-threading.lua:38>
	[C]: in function 'xpcall'
	/engine/interface/ActorTalents.lua:171: in function </engine/interface/ActorTalents.lua:160>
	At [C]:-1 
	At [C]:-1 error
	At /engine/interface/ActorTalents.lua:333 useTalent
	At /engine/interface/PlayerHotkeys.lua:170 
	At /engine/interface/PlayerHotkeys.lua:162 activateHotkey
	At /engine/HotkeysIconsDisplay.lua:384 onMouse
	At /mod/class/uiset/Minimalist.lua:1820 fct
	At /engine/Mouse.lua:58 
FROM 	/mod/addons/cults/superload/engine/dialogs/ShowErrorStack.lua	loading previous!
[ENGINE] Setting requested FPS to 2 (500 ms)
[ENGINE] Setting requested FPS to 30 (33 ms)
[PROFILE] Thread connecting to profiles.te4.org on ports 	2257	2258
[ENGINE] Setting requested FPS to 2 (500 ms)
[ENGINE] Setting requested FPS to 30 (33 ms)
[ENGINE] Setting requested FPS to 2 (500 ms)
[PlayerProfile] eventDisconnected
[PROFILE] Thread connecting to profiles.te4.org on ports 	2257	2258
[ENGINE] Setting requested FPS to 30 (33 ms)
[PlayerProfile] eventDisconnected
Deleting temp shader	resources2[amp=0.8,color1=vec3(0.1843137254902,0.62745098039216,0.70588235294118),color2=vec3(0.56078431372549,0.50196078431373,0.26666666666667),color=vec3(0.25490196078431,0.59607843137255,0.86274509803922),distort=vec2(0.1,0.25),require_shader=4,speed=20000]
Deleting temp shader	resources[color=vec3(0.75294117647059,0,0),distort=vec2(1.5,1.5),require_shader=4,speed=1000]
Deleting temp shader	resources[color=vec3(1,0.84313725490196,0),distort=vec2(1.6,0.2),require_shader=4,speed=1000]
[ENGINE] Setting requested FPS to 2 (500 ms)
[PROFILE] Thread connecting to profiles.te4.org on ports 	2257	2258
[PlayerProfile] eventDisconnected
[ENGINE] Setting requested FPS to 30 (33 ms)
[logerr]%s casts %s.
[LOG]	555 施展了 扭曲灵刃 。
[PROFILE] Thread connecting to profiles.te4.org on ports 	2257	2258
orb weaver	23042	dumb ai talents can use	蜘蛛之网	T_SPIDER_WEB
orb weaver	23042	dumb ai talents can use	攻击	T_ATTACK
orb weaver	23042	dumb ai talents can use	撒网	T_LAY_WEB
dumb ai uses	T_LAY_WEB
[logerr]%s seems to search the ground...
[LOG]	球蛛编织者 似乎在地面上搜寻着什么...
Loading tile from tileset	/data/gfx/talents/lay_web.png
[logerr]
[LOG]	
[logerr]%s casts %s.
[LOG]	555 施展了 扭曲灵刃 。
[ATTACK] attacking with (mainhand)	iron longsword
[ATTACK] to 	orb weaver	 :: 	15.334331517708	2	2	20	vs.	7	::	1.6768882040742
[ATTACK] after melee attack bonus hooks and callbacks :: 	15.334331517708	2	2	20	vs.	7	::	1.6768882040742
checkHit	20	vs	7	=> chance to hit	83
[ATTACK] raw dam	15.334331517708	versus	2	0.3	with APR	2
[ATTACK] after armor	15.334331517708
[ATTACK] after range	16
[PHYS CRIT %]	2.5
[ATTACK] after crit	16
[ATTACK] after mult	26.830211265188
[ATTACK] attacking with (offhand)	iron dagger
[ATTACK] to 	orb weaver	 :: 	13.624672811725	5	2	20	vs.	7	::	0.83844410203712
[ATTACK] after melee attack bonus hooks and callbacks :: 	13.624672811725	5	2	20	vs.	7	::	0.83844410203712
checkHit	20	vs	7	=> chance to hit	83
[ATTACK] dagger accuracy bonus	20	7	=	1.065	previous	5
[ATTACK] raw dam	13.624672811725	versus	2	0.3	with APR	5.325
[ATTACK] after armor	13.624672811725
[ATTACK] after range	17
[PHYS CRIT %]	4
[ATTACK] after crit	17
[ATTACK] after mult	14.253549734631
[SOUND] loading from	/data/sound/actions/melee.lua	:=:	/data/sound/actions/melee.ogg	:>
[SOUND] :=>	sound "/data/sound/actions/melee.ogg" : <static>
[SOUND] loading from	/data/sound/actions/melee_hit_squish.lua	:=:	/data/sound/actions/melee_hit_squish.ogg	:>
[SOUND] :=>	sound "/data/sound/actions/melee_hit_squish.ogg" : <static>
logMsgCheck	#Source# hits #Target# for %s (%0.0f total damage)%s.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#15 时空#LAST#, #WHITE#12 物理#LAST#, #LIGHT_STEEL_BLUE#8 时空#LAST#, #WHITE#6 物理#LAST# (41 合计伤害).
[logerr]#UID:2870:0##fbd578#555#LAST# 击中 球蛛编织者 造成 #LIGHT_STEEL_BLUE#15 时空#LAST#, #WHITE#12 物理#LAST#, #LIGHT_STEEL_BLUE#8 时空#LAST#, #WHITE#6 物理#LAST# (41 合计伤害).
[LOG]	#UID:2870:0##fbd578#555#LAST# 击中 球蛛编织者 造成 #LIGHT_STEEL_BLUE#15 时空#LAST#, #WHITE#12 物理#LAST#, #LIGHT_STEEL_BLUE#8 时空#LAST#, #WHITE#6 物理#LAST# (41 合计伤害).
logMsgCheck	#{bold}##Source# killed #Target#!#{normal}#
logMsgTrans	#{bold}##Source# 击杀了 #Target#!#{normal}#
logMsgCheck	#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
logMsgTrans	#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
logMsgCheck	#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
logMsgTrans	#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
[logerr]#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
[LOG]	#{bold}##UID:2870:0##fbd578#555#LAST# 击杀了 球蛛编织者!#{normal}#
orb spinner	17052	dumb ai talents can use	时空之箭	T_TEMPORAL_BOLT
dumb ai uses	T_TEMPORAL_BOLT
[logerr]%s casts %s.
[LOG]	球蛛纺织者 施展了 时空之箭 。
[SPELL CRIT %]	1
Adding entity	23125	after	17052
[SOUND] loading from	/data/sound/talents/spell_generic2.ogg	:=:	sound "/data/sound/talents/spell_generic2.ogg" : <static>
Loading tile from tileset	/data/gfx/talents/temporal_bolt.png
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
[logerr]#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
[LOG]	#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
[logerr]
[LOG]	
[logerr]@Target@ is caught in a web!
[LOG]	555 陷入网中！
checkHit	7	vs	19.0625	=> chance to hit	20
[logerr]#Target# is pinned to the ground.
[LOG]	555 被定身在原地。
Loading tile from tileset	/data/gfx/shockbolt/trap/trap_spiderweb_01_64.png
Loading tileset	/data/gfx/ts-gfx-trap1.png
orb spinner	17073	dumb ai talents can use	时空之箭	T_TEMPORAL_BOLT
dumb ai uses	T_TEMPORAL_BOLT
[SPELL CRIT %]	1
Adding entity	23126	after	17073
orb weaver	23073	dumb ai talents can use	蜘蛛之网	T_SPIDER_WEB
orb weaver	23073	dumb ai talents can use	撒网	T_LAY_WEB
dumb ai uses	T_SPIDER_WEB
checkHit	7	vs	10	=> chance to hit	43
[logerr]#ORANGE#%s shrugs off the effect '%s'!
[LOG]	#ORANGE#555 豁免了“ 定身 ”效果！
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
[logerr]某物 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
[LOG]	某物 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#10 时空#LAST# 伤害。
Loading tile from tileset	/data/gfx/effects/pinned.png
[logerr]
[LOG]	
[PlayerProfile] eventDisconnected
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Loading tile from tileset	/data/gfx/shockbolt/object/sword_iron.png
Loading tile from tileset	/data/gfx/shockbolt/object/knife_iron.png
[logerr]%s switches %s weapons to: %s.
Lua Error: data-chn123/logs/class.lua:1615: attempt to call method 'gsub' (a nil value)
	At [C]:-1 gsub
	At data-chn123/logs/class.lua:1615 fct
	At /data-chn123/logs.lua:22 trans
	At /engine/LogDisplay.lua:126 logdisplay
	At /mod/class/uiset/Minimalist.lua:495 log
	At /mod/class/Game.lua:1525 logSeen
	At /mod/class/Actor.lua:3842 quickSwitchWeapons
	At /mod/dialogs/ShowEquipInven.lua:197 switchSets
	At /mod/dialogs/ShowEquipInven.lua:45 on_change
	At /engine/ui/Tab.lua:93 select
	At /engine/ui/Tab.lua:54 fct
	At /engine/Mouse.lua:58 receiveMouse
	At /engine/Mouse.lua:98 delegate
	At /data-chn123/dialog.lua:842 mouseEvent
	At /data-chn123/dialog.lua:562 fct
	At /engine/Mouse.lua:58 
orb spinner	17052	dumb ai talents can use	攻击	T_ATTACK
dumb ai uses	T_ATTACK
[ATTACK] attacking with innate combat
[ATTACK] to 	555	 :: 	6.4940332439102	3	2	16	vs.	2	::	1
[ATTACK] after melee attack bonus hooks and callbacks :: 	6.4940332439102	3	2	16	vs.	2	::	1
checkHit	16	vs	2	=> chance to hit	85
[ATTACK] raw dam	6.4940332439102	versus	2	0.3	with APR	3
[ATTACK] after armor	6.4940332439102
[ATTACK] after range	6
[PHYS CRIT %]	1
[ATTACK] after crit	6
[ATTACK] after mult	6
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[LOG]	#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]
[LOG]	
[logerr]%s switches %s weapons to: %s.
Lua Error: data-chn123/logs/class.lua:1615: attempt to call method 'gsub' (a nil value)
	At [C]:-1 gsub
	At data-chn123/logs/class.lua:1615 fct
	At /data-chn123/logs.lua:22 trans
	At /engine/LogDisplay.lua:126 logdisplay
	At /mod/class/uiset/Minimalist.lua:495 log
	At /mod/class/Game.lua:1525 logSeen
	At /mod/class/Actor.lua:3842 quickSwitchWeapons
	At /mod/dialogs/ShowEquipInven.lua:197 switchSets
	At /mod/dialogs/ShowEquipInven.lua:45 on_change
	At /engine/ui/Tab.lua:93 select
	At /engine/ui/Tab.lua:54 fct
	At /engine/Mouse.lua:58 receiveMouse
	At /engine/Mouse.lua:98 delegate
	At /data-chn123/dialog.lua:842 mouseEvent
	At /data-chn123/dialog.lua:562 fct
	At /engine/Mouse.lua:58 
[ATTACK] attacking with innate combat
[ATTACK] to 	555	 :: 	6.4940332439102	3	2	16	vs.	2	::	1
[ATTACK] after melee attack bonus hooks and callbacks :: 	6.4940332439102	3	2	16	vs.	2	::	1
checkHit	16	vs	2	=> chance to hit	85
[ATTACK] raw dam	6.4940332439102	versus	2	0.3	with APR	3
[ATTACK] after armor	6.4940332439102
[ATTACK] after range	7
[PHYS CRIT %]	1
[ATTACK] after crit	7
[ATTACK] after mult	7
[logerr]#Target# is no longer pinned.
[LOG]	555 摆脱了定身。
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[LOG]	#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]
[LOG]	
[logerr]%s shoots!
[LOG]	555 射击！
[logerr]%s warps space-time to equip: %s.
##Use Talent Lua Error##	T_SHOOT	Actor:	2870	555
Lua Error: /engine/interface/ActorTalents.lua:333: /engine/interface/ActorTalents.lua:306: /engine/interface/ActorTalents.lua:173: data-chn123/logs/class.lua:1607: attempt to call method 'gsub' (a nil value)
stack traceback:
	data-chn123/logs/class.lua:1607: in function 'fct'
	/data-chn123/logs.lua:22: in function 'trans'
	/engine/LogDisplay.lua:126: in function 'logdisplay'
	/mod/class/uiset/Minimalist.lua:495: in function 'log'
	/mod/class/Game.lua:1525: in function 'logSeen'
	/mod/class/Actor.lua:3840: in function 'quickSwitchWeapons'
	/data/talents/chronomancy/chronomancer.lua:259: in function 'doWardenWeaponSwap'
	/data/talents/techniques/archery.lua:125: in function </data/talents/techniques/archery.lua:124>
	[C]: in function 'xpcall'
	/engine/interface/ActorTalents.lua:171: in function </engine/interface/ActorTalents.lua:160>
	At [C]:-1 
	At [C]:-1 error
	At /engine/interface/ActorTalents.lua:333 useTalent
	At /mod/class/Game.lua:2500 mouseLeftClick
	At /mod/class/Game.lua:2472 fct
	At /engine/Mouse.lua:58 
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
Using cached font	/data-chn123/font/main.ttf	10
[logerr]%s switches %s weapons to: %s.
Lua Error: data-chn123/logs/class.lua:1615: attempt to call method 'gsub' (a nil value)
	At [C]:-1 gsub
	At data-chn123/logs/class.lua:1615 fct
	At /data-chn123/logs.lua:22 trans
	At /engine/LogDisplay.lua:126 logdisplay
	At /mod/class/uiset/Minimalist.lua:495 log
	At /mod/class/Game.lua:1525 logSeen
	At /mod/class/Actor.lua:3842 quickSwitchWeapons
	At /mod/dialogs/ShowEquipInven.lua:197 switchSets
	At /mod/dialogs/ShowEquipInven.lua:45 on_change
	At /engine/ui/Tab.lua:93 select
	At /engine/ui/Tab.lua:54 fct
	At /engine/Mouse.lua:58 receiveMouse
	At /engine/Mouse.lua:98 delegate
	At /data-chn123/dialog.lua:842 mouseEvent
	At /data-chn123/dialog.lua:562 fct
	At /engine/Mouse.lua:58 
AI took for target	17052	orb spinner	::	2870	555	1	<	100
[ATTACK] attacking with innate combat
[ATTACK] to 	555	 :: 	6.4940332439102	3	2	16	vs.	2	::	1
[ATTACK] after melee attack bonus hooks and callbacks :: 	6.4940332439102	3	2	16	vs.	2	::	1
checkHit	16	vs	2	=> chance to hit	85
[ATTACK] raw dam	6.4940332439102	versus	2	0.3	with APR	3
[ATTACK] after armor	6.4940332439102
[ATTACK] after range	6
[PHYS CRIT %]	1
[ATTACK] after crit	6
[ATTACK] after mult	6
[logerr]#00ff00#%sTalent %s is ready to use.
[LOG]	#00ff00##UID:1189:0#技能 重叠灵矢 已经可以使用。
AI took for target	23073	orb weaver	::	2870	555	9	<	100
logMsgCheck	#Source# hits #Target# for %s damage.
logMsgTrans	#Source# 击中 #Target# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[LOG]	#UID:17052:0#球蛛纺织者 击中 #fbd578#555#LAST# 造成 #LIGHT_STEEL_BLUE#5 时空#LAST# 伤害。
[logerr]
[LOG]	
[logerr]%s shoots!
[LOG]	555 射击！
[logerr]%s warps space-time to equip: %s.
##Use Talent Lua Error##	T_SHOOT	Actor:	2870	555
Lua Error: /engine/interface/ActorTalents.lua:333: /engine/interface/ActorTalents.lua:306: /engine/interface/ActorTalents.lua:173: data-chn123/logs/class.lua:1607: attempt to call method 'gsub' (a nil value)
stack traceback:
	data-chn123/logs/class.lua:1607: in function 'fct'
	/data-chn123/logs.lua:22: in function 'trans'
	/engine/LogDisplay.lua:126: in function 'logdisplay'
	/mod/class/uiset/Minimalist.lua:495: in function 'log'
	/mod/class/Game.lua:1525: in function 'logSeen'
	/mod/class/Actor.lua:3840: in function 'quickSwitchWeapons'
	/data/talents/chronomancy/chronomancer.lua:259: in function 'doWardenWeaponSwap'
	/data/talents/techniques/archery.lua:125: in function </data/talents/techniques/archery.lua:124>
	[C]: in function 'xpcall'
	/engine/interface/ActorTalents.lua:171: in function </engine/interface/ActorTalents.lua:160>
	At [C]:-1 
	At [C]:-1 error
	At /engine/interface/ActorTalents.lua:333 useTalent
	At /mod/class/Game.lua:2500 mouseLeftClick
	At /mod/class/Game.lua:2472 fct
	At /engine/Mouse.lua:58

**Comment by StarSapphireX** [comment]
已确认
